site_name: pyControl Tutorial
site_description: A tutorial and cookbook for pyControl
site_author: Andy Lustig
repo_url: https://github.com/alustig3/pycontrol-cookbook
repo_name: alustig3/pycontrol-cookbook
copyright: Copyright &copy; 2025 Andy Lustig
site_dir: docs/

extra:
    discussion_url: https://github.com/alustig3/pycontrol-cookbook/discussions
    issues_url: https://github.com/alustig3/pycontrol-cookbook/issues
#     version:
#         provider: mike

nav:
    - Overview: index.md
    - Tutorial: tutorial.md
    - Cookbook: cookbook.md

docs_dir: src

theme:
    name: material
    custom_dir: overrides
    logo: custom/home.svg
    palette:
        primary: teal
        accent: teal
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.sections
        - navigation.footer
        - navigation.instant
        - content.code.copy
        - content.code.annotate


extra_css:
    - custom/extra.css

plugins:
    - search
    - include-markdown:
          comments: false

markdown_extensions:
    - toc:
          title: On this page
          permalink: "#"
          toc_depth: 3
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.blocks.caption
    - pymdownx.critic
    - pymdownx.snippets:
          base_path: src
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
